#!/usr/bin/perl
use warnings;
use strict;
use Text::GFMarkdown::Lex;
use Text::GFMarkdown::Parse;
use Text::GFMarkdown::Compile;
use Data::Dumper;

my $content = $ARGV[0];

print "\033[33mTokens From Lexer\033[0m\n";

my @lex = Text::GFMarkdown::Lex->new->lex($content);
print Dumper @lex;

print "\033[33mParse Tree\033[0m\n";

my @tree = Text::GFMarkdown::Parse->new->parse(@lex);
print Dumper @tree;

print "\033[33mFinal String\033[0m\n";

my $str = Text::GFMarkdown::Compile->new->compile(@tree);
print Dumper $str;

